// Code generated by protoc-gen-go.
// source: request.proto
// DO NOT EDIT!

/*
Package zrpc is a generated protocol buffer package.

It is generated from these files:
	request.proto
	response.proto

It has these top-level messages:
	Request
*/
package zrpc

import proto "github.com/golang/protobuf/proto"
import math "math"

// discarding unused import gogoproto "github.com/gogo/protobuf/gogoproto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

// Request is an envelope for sending a request from a client to a service
type Request struct {
	UUID             []byte  `protobuf:"bytes,1,opt" json:"UUID,omitempty"`
	Path             *string `protobuf:"bytes,2,opt,name=path" json:"path,omitempty"`
	Payload          []byte  `protobuf:"bytes,3,opt,name=payload" json:"payload,omitempty"`
	Expires          *int64  `protobuf:"varint,4,opt,name=expires" json:"expires,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}

func (m *Request) GetUUID() []byte {
	if m != nil {
		return m.UUID
	}
	return nil
}

func (m *Request) GetPath() string {
	if m != nil && m.Path != nil {
		return *m.Path
	}
	return ""
}

func (m *Request) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Request) GetExpires() int64 {
	if m != nil && m.Expires != nil {
		return *m.Expires
	}
	return 0
}
