// Code generated by protoc-gen-go.
// source: reverseservice.proto
// DO NOT EDIT!

/*
Package reverseservicepb is a generated protocol buffer package.

It is generated from these files:
	reverseservice.proto

It has these top-level messages:
	ReverseRequest
	ReverseResponse
*/
package reverseservicepb

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type ReverseRequest struct {
	NormalString     *string `protobuf:"bytes,1,req,name=normal_string" json:"normal_string,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ReverseRequest) Reset()         { *m = ReverseRequest{} }
func (m *ReverseRequest) String() string { return proto.CompactTextString(m) }
func (*ReverseRequest) ProtoMessage()    {}

func (m *ReverseRequest) GetNormalString() string {
	if m != nil && m.NormalString != nil {
		return *m.NormalString
	}
	return ""
}

type ReverseResponse struct {
	ReversedString   *string `protobuf:"bytes,1,req,name=reversed_string" json:"reversed_string,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ReverseResponse) Reset()         { *m = ReverseResponse{} }
func (m *ReverseResponse) String() string { return proto.CompactTextString(m) }
func (*ReverseResponse) ProtoMessage()    {}

func (m *ReverseResponse) GetReversedString() string {
	if m != nil && m.ReversedString != nil {
		return *m.ReversedString
	}
	return ""
}
